version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/ci/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
  - package-ecosystem: "cargo"
    directory: "/src/ffi"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "rust"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
