name: OCCT CI
on:
  push:
    branches: [master, dev-occt**]
    paths:
      - "src/occt/**"
      - "src/ffi/**"
      - "test/occt/**"
      - "test/ffi/**"
      - "ci/**"
      - ".github/**"
      - "./CMakeLists.txt"
  pull_request:
    branches: [master, dev-occt]
    paths:
      - "src/occt/**"
      - "src/ffi/**"
      - "test/occt/**"
      - "test/ffi/**"
      - "ci/**"
      - ".github/**"
      - "./CMakeLists.txt"

jobs:
  build-wrappers:
    name: Build OCCT wrappers
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Make script executable
        run: chmod +x ./ci/scripts/occt.sh

      - name: Build OCCT and run tests
        run: ./ci/scripts/occt.sh --unit-testing

      - name: Tag and push OCCT image
        if: github.event_name != 'pull_request'
        run: |
          docker tag occt-builder:latest ghcr.io/${{ github.repository }}/occt-builder:latest
          docker push ghcr.io/${{ github.repository }}/occt-builder:latest
