name: OCCT CI

on:
  push:
    branches: [master, dev-occt**]
    paths:
      - "src/occt/**"
      - "src/ffi/**"
      - "test/occt/**"
      - "test/ffi/**"
      - "ci/**"
      - ".github/**"
      - "./CMakeLists.txt"
  pull_request:
    branches: [master, dev-occt]
    paths:
      - "src/occt/**"
      - "src/ffi/**"
      - "test/occt/**"
      - "test/ffi/**"
      - "ci/**"
      - ".github/**"
      - "./CMakeLists.txt"

jobs:
  build-wrappers:
    name: Build OCCT wrappers
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Make script executable
        run: chmod +x ./ci/scripts/occt.sh

      - name: Build OCCT and run tests
        run: ./ci/scripts/occt.sh --unit-testing

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: occt-build-artifacts
          path: |
            build/
            **/*.so
            **/*.a
          retention-days: 7
